server:
  port: 8900
spring:
  application:
    name: blob-article
  cloud:
    nacos:
      server-addr: 10.216.86.184:9999
      discovery:
        username: nacos
        password: nacos
        namespace: public

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nacos
    username: root
    password: wangxu
    type: com.alibaba.druid.pool.DruidDataSource



